name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs every 2 hours
    - cron: "* * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          TIME_RANGE: all_time
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
         